file:
  # 분석 파일 저장 상위경로
  save_root_dir: /data1
  # 분석 로그 파일 저장 기한 (기본 값: 7)
  log_period: 7
  # pcap 파일 저장 기한 (기본 값: 7)
  pcap_period: 7

interface:
  # 패킷 수집 인터페이스 목록 (기본 값 : 모든 인터페이스)
  target: ens18
  # 패킷 BPF 필터 문자열
  filter: tcp

suricata:
  # Suricata에서 pcap을 읽은 로그를 저장할 경로
  log_dir: /data1/temp_suricata
  # Suricata 룰 파일 저장 경로
  rule_dir: /var/lib/suricata/rules
  # Suricata 룰 파일 목록
  rule_file_name_list:
    - suricata.rules
    - xa_ids.rules
  # Suricata 설정 파일 경로
  config_file_path: /etc/suricata/elixcore_suricata.yaml
